name: Continuous integration checks

on:
  pull_request:
    branches: [ "main" ]
    max-concurrency: 3
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
    max-concurrency: 3

jobs:
  build-run-tests:
    name: Builds and runs tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build and test in containers
        id: build-test-in-containers
        run: |
          cd $GITHUB_WORKSPACE/build-automation && ALUS_ENABLE_TESTS=ON ./build_in_containers.sh $GITHUB_WORKSPACE /tmp/ cgialus/alus-ootpa-devel:latest cgialus/alus-devel:latest
      - name: Test report generation
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test report
          path: '/tmp/alus-ootpa-devel/unit-test/results/*.xml,/tmp/alus-devel/unit-test/results/*.xml'
          reporter: java-junit