name: End-to-end tests on AWS GPU instance

on:
  pull_request:
    branches: [ "main" ]
    max-concurrency: 1
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
    max-concurrency: 1

jobs:
  start-gpu-instance:
    name: Start GPU instance
    runs-on: ubuntu-latest
    outputs:
      instance_ip: ${{ steps.trigger_instance.outputs.instance_ip }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.FALCON_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.FALCON_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EAGLE_INSTANCE_REGION }}
      - uses: actions/checkout@v3
      - name: Trigger the instance
        id: trigger_instance
        run: |
          set -o pipefail
          $GITHUB_WORKSPACE/build-automation/trigger_ec2_instance.sh ${{ secrets.EAGLE_INSTANCE_ID }} | tee trigger_out.txt
          ip_address=$(cat trigger_out.txt | tail -n 1)
          echo "instance_ip=$ip_address" >> $GITHUB_OUTPUT
          sleep 5

  end-to-end-testing:
    name: End-to-end testing
    runs-on: ubuntu-latest
    needs: start-gpu-instance
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Create SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EAGLE_SSH_KEY }}
        run: |
          key_location=~/.ssh/
          mkdir -p $key_location
          key_path=$key_location/id_rsa
          echo "$SSH_PRIVATE_KEY" > $key_path
          sudo chmod 600 $key_path
          ssh-keygen -f $key_path -y > $key_path.pub
      - name: Transfer package
        id: transfer_package
        env:
          INSTANCE_USERNAME: ${{ secrets.EAGLE_USERNAME }}
        run: |
          instance_ip=${{ needs.start-gpu-instance.outputs.instance_ip }}
          scp -o "StrictHostKeyChecking no" -r $GITHUB_WORKSPACE $INSTANCE_USERNAME@instance_ip:/tmp/
#          Tere
#          ssh -o "StrictHostKeyChecking no" $INSTANCE_USERNAME@$instance_ip "rm -rf $instance_package_dir"
#          ssh -o "StrictHostKeyChecking no" $INSTANCE_USERNAME@$instance_ip "mkdir $instance_package_dir"
#          scp -o "StrictHostKeyChecking no" $package_filename $INSTANCE_USERNAME@$instance_ip:$instance_package_dir/
#          echo "instance_package_dir=$instance_package_dir" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: End-to-end tests
        env:
          INSTANCE_USERNAME: ${{ secrets.ALUS_ALEX_USERNAME }}
        run: |
          instance_ip=${{ needs.start-gpu-instance.outputs.instance_ip }}
#          package_dir=${{ steps.transfer_package.outputs.instance_package_dir }}
#          build_id=${{ needs.release-package.outputs.package_name }}
#          scp -o "StrictHostKeyChecking no" build-automation/*.py build-automation/*.sh build-automation/*.txt $INSTANCE_USERNAME@$instance_ip:$package_dir/
#          ssh -oStrictHostKeyChecking=no $INSTANCE_USERNAME@$instance_ip "export NIGHTLY_GOLDEN_DIR=/home/$INSTANCE_USERNAME/e2e/golden; export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64/:\$LD_LIBRARY_PATH; cd $package_dir; ./execute_e2e.sh $build_id e2e_resources.txt"

  stop-gpu-instance:
    name: Stop GPU instance
    runs-on: ubuntu-latest
    needs: [start-gpu-instance, end-to-end-testing]
    if: |
      always() &&
      needs.start-gpu-instance.result == 'success'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.FALCON_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.FALCON_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EAGLE_INSTANCE_REGION }}
      - uses: actions/checkout@v3
      - name: Stop GPU instance
        run: |
          $GITHUB_WORKSPACE/build-automation/stop_ec2_instance.sh ${{ secrets.EAGLE_INSTANCE_ID }}
